# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G99vMS8BHuCbYUE-8HFBgh8s2UjrRwnS
"""

student_name = input("Enter student name: ")
student_course = input("Enter student's course: ")

modules = {}

num_modules = int(input("Enter number of modules: "))

for i in range(num_modules):
    print(f"\nModule {i + 1}")

    module_name = input("Enter module name: ")
    total_classes = int(input("Enter total classes held: "))
    classes_attended = int(input("Enter classes attended: "))

    if total_classes <= 0:
        print("Error: Total classes must be greater than 0.")
        continue

    if classes_attended < 0 or classes_attended > total_classes:
        print("Error: Classes attended must be between 0 and total classes.")
        continue

    attendance_percentage = (classes_attended / total_classes) * 100
    modules[module_name] = attendance_percentage

print("\n" + "=" * 40)
print("ATTENDANCE REPORT")
print("=" * 40)
print("Student Name:", student_name)2
print("Course:", student_course)

for module, percentage in modules.items():
    status = "Allowed for exam" if percentage >= 75 else "Not allowed for exam"

    print(f"\nModule: {module}")
    print(f"Attendance: {percentage:.2f}%")
    print(f"Status: {status}")